import jsPDF from 'jspdf';
import 'jspdf-autotable';

export async function generateFinancialPDF(data: any) {
    const doc = new jsPDF() as any;

    // Background accent
    doc.setFillColor(15, 23, 42); // Navy
    doc.rect(0, 0, 210, 40, 'F');

    // Header
    doc.setFontSize(24);
    doc.setTextColor(251, 191, 36); // Mahanka Gold
    doc.text('MAHANKA CFO', 14, 25);

    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text('Institutional Financial Orchestration | v1.5', 14, 32);

    // Confidence Meter (Top Right)
    const confidence = data.confidence || 92;
    const color = confidence > 90 ? [34, 197, 94] : [251, 191, 36]; // Green or Gold
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(140, 18, 55, 10, 2, 2, 'F');
    doc.setFillColor(...color);
    doc.roundedRect(140, 18, (confidence / 100) * 55, 10, 2, 2, 'F');

    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(`CONFIDENCE: ${confidence}%`, 148, 24.5);

    // Hero Numbers Section
    let yPos = 65;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.text('ESTIMATED CASHFLOW', 14, yPos);
    doc.text('GROSS MARGIN', 100, yPos);

    yPos += 12;
    doc.setFontSize(36);
    doc.setTextColor(15, 23, 42);
    doc.text(`$${data.cashflow || '124,500'}`, 14, yPos);
    doc.text(`${data.margin || '32.4%'}`, 100, yPos);

    // Watermark (DRAFT STAMP)
    doc.setTextColor(255, 0, 0);
    doc.setFontSize(40);
    doc.setFont('helvetica', 'bold');
    doc.text('DRAFT — CA REVIEW REQUIRED', 105, 150, { align: 'center', angle: 45 });

    // The Real Talk (Executive Summary)
    yPos += 30;
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(10, yPos - 10, 190, 60, 4, 4, 'F');

    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text('The Real Talk', 14, yPos + 5);

    yPos += 15;
    doc.setFontSize(12);
    doc.setTextColor(71, 85, 105);
    const splitText = doc.splitTextToSize(data.summary || 'Monthly reconciliation completed. High confidence in Shopify data; manual fulfillment logs pending verification for 100% completeness.', 180);
    doc.text(splitText, 14, yPos);

    // Footer / Metadata
    yPos = 275;
    doc.setFontSize(7);
    doc.setTextColor(239, 68, 68); // Red-500
    doc.text('REGULATORY BOUNDARY: Mahanka provides automated drafts. Final compliance remains with professional.', 105, yPos, { align: 'center' });

    yPos = 285;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Report generated by Close Engine | ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 14, yPos);
    doc.text('Confidential | Powered by Mahanka Intelligence', 140, yPos);

    const pdfOutput = doc.output('datauristring');
    return pdfOutput;
}
