import jsPDF from 'jspdf';
import 'jspdf-autotable';

export async function generateFinancialPDF(data: any) {
    const doc = new jsPDF() as any;

    // Header
    doc.setFontSize(24);
    doc.setTextColor(5, 11, 24); // Mahanka Navy
    doc.text('Mahanka CFO Report', 14, 25);

    // Confidence Meter
    const confidence = data.confidence || 92;
    const color = confidence > 90 ? [34, 197, 94] : [234, 179, 8];
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(140, 18, 50, 8, 2, 2, 'F');
    doc.setFillColor(...color);
    doc.roundedRect(140, 18, (confidence / 100) * 50, 8, 2, 2, 'F');

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`CONFIDENCE: ${confidence}%`, 147, 23.5);

    doc.text(`Generated by Close Engine (v1.0) | Always by the 10th`, 14, 32);

    doc.setLineWidth(0.5);
    doc.line(14, 40, 196, 40);

    // Hero Numbers
    let yPos = 55;
    doc.setFontSize(12);
    doc.setTextColor(150);
    doc.text('ESTIMATED CASHFLOW', 14, yPos);
    doc.text('UNIT MARGIN', 100, yPos);

    yPos += 12;
    doc.setFontSize(28);
    doc.setTextColor(5, 11, 24);
    doc.text(`$${data.cashflow || '124.5k'}`, 14, yPos);
    doc.text(`${data.margin || '32%'}`, 100, yPos);

    // Executive Summary
    yPos += 20;
    doc.setFontSize(16);
    doc.text('The Real Talk', 14, yPos);

    yPos += 10;
    doc.setFontSize(11);
    doc.setTextColor(60);
    const splitText = doc.splitTextToSize(data.summary || 'Monthly reconciliation completed. High confidence in Shopify data; manual fulfillment logs pending verification.', 180);
    doc.text(splitText, 14, yPos);

    yPos += splitText.length * 7 + 10;
    doc.setFontSize(10);
    doc.setTextColor(180);
    doc.text('Human-in-the-loop verification required for disbursement actions.', 14, yPos);

    // Save/Return
    const pdfOutput = doc.output('datauristring');
    return pdfOutput;
}
